### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rysson** [rysson/filmkodi#2]
TODO
=====

Ogólny plan reanimacji wtyczek MrKnow.
------------------------------------------------------

* [ ] Najmniejsze łaty uruchamiające wtyczki
  * [ ] fanfilm – do likwidacji na 99%, [notoco](https://github.com/notoco/ffl) rozwija wtyczkę
  * [ ] mrknow (*Filmy Online*)
  * [ ] mrknowtv 
  * [ ] wizjatv – do likwidacji, [kodiver](https://github.com/neopack1/plugin.video.kodiver.wizjatv) napisał swoją, ew. do zintegrowania
  * [ ] xbmcfilm
  * [ ] urlresolver – do likwidacji
* [ ] Integracja z istniejącym kodem (np. resolver)
* [ ] Refactoring
